from enum import Enum

__all__ = (
    'ReportType',
    'StatisticsReportType',
)


class ReportType(Enum):
    STATISTICS = 'STATISTICS'
    INGREDIENTS_STOP_SALES = 'INGREDIENTS_STOP_SALES'
    STREET_STOP_SALES = 'STREET_STOP_SALES'
    SECTOR_STOP_SALES = 'SECTOR_STOP_SALES'
    PIZZERIA_STOP_SALES = 'PIZZERIA_STOP_SALES'
    STOPS_AND_RESUMES = 'STOPS_AND_RESUMES'
    CANCELED_ORDERS = 'CANCELED_ORDERS'
    CHEATED_PHONE_NUMBERS = 'CHEATED_PHONE_NUMBERS'


class StatisticsReportType(Enum):
    COOKING_TIME = 'COOKING_TIME'
    RESTAURANT_COOKING_TIME = 'RESTAURANT_COOKING_TIME'
    KITCHEN_PERFORMANCE = 'KITCHEN_PERFORMANCE'
    DELIVERY_AWAITING_TIME = 'DELIVERY_AWAITING_TIME'
    DELIVERY_SPEED = 'DELIVERY_SPEED'
    DELIVERY_PERFORMANCE = 'DELIVERY_PERFORMANCE'
    BEING_LATE_CERTIFICATES = 'BEING_LATE_CERTIFICATES'
    DAILY_REVENUE = 'DAILY_REVENUE'
    AWAITING_ORDERS = 'AWAITING_ORDERS'
    BONUS_SYSTEM = 'BONUS_SYSTEM'
    PRODUCTIVITY_BALANCE = 'PRODUCTIVITY_BALANCE'
